package com.example.CRM.enums;

public enum Commands {

    NEWLEAD, SHOWLEADS, SHOWOPPORTUNITIES,
    SHOWACCOUNTS, SHOWSALESREP, LOOKUPLEAD, LOOKUPOPPORTUNITY,
    LOOKUPACCOUNT, CONVERT, CLOSED_WON,
    CLOSED_LOST, NEWSALESREP, HELP, EXIT

}
